Added Sharding section
Vettabase/awesome-mariadb pull request #11
Opened 2024-06-28 08:31 UTC by rcbensley

Adding some common sharding options.

2024-06-28 09:08 UTC, federico-razzoli requested changes
Some notes:
- Modify the intro text to make it clear that there is no complete sharding solution for MariaDB, but we can shard the data with a dedicated storage engine and route the queries to the right shards with a proxy.
- Keep the items in alphabetical order.
- As "Project" I'd indicate the software, eg, ProxySQL. I'd add a Notes column to briefly explain how it's useful for sharding (eg, routes queries based on a regexp).

2024-06-28 15:38 UTC, federico-razzoli requested changes

2024-06-28 15:38 UTC, federico-razzoli commented on list-dba.md
> +Sharding solutions require evalation depending in your applications requirements. Some solutions are internal and shard with the application being unaware, or externally use rules and defititions whi
Spider and proxies might be parts of the same sharded setup, but then you'll have to configure them, write scripts to add/remove/resize shards, possibly use replication to distribute some shared data to all the shards, etc. So I'd just write that a complete sharding solution doesn't exist, there are components that solve some aspects of the problem.

2024-07-04 12:23 UTC, federico-razzoli requested changes

2024-07-04 12:23 UTC, federico-razzoli commented on list-dba.md
> +| [CONNECT](https://mariadb.com/kb/en/using-connect-partitioning-and-sharding/) | YES   | GPLv2              | A storage engine. An outward table can be partitioned over serveral remote tables repres
It's true that CONNECT has this feature, but I wouldn't consider it for this purpose. Better to use SPIDER.

2024-07-05 14:56 UTC, rcbensley commented
Added vitess sharding docs which is more complete than other solutions but not magic by itself.

2024-07-05 16:07 UTC, rcbensley commented on list-dba.md
> +| [CONNECT](https://mariadb.com/kb/en/using-connect-partitioning-and-sharding/) | YES   | GPLv2              | A storage engine. An outward table can be partitioned over serveral remote tables repres
Removed the engine from sharding

2024-07-05 17:09 UTC, federico-razzoli requested changes

2024-07-05 17:09 UTC, federico-razzoli commented on list-dba.md
> +| [Vitess](https://vitess.io/docs/19.0/reference/features/sharding/)  | Yes             | Apache 2.0         | Vitess is external to the database engine and also has migration strategies built in. |
But it doesn't support MariaDB. It did for some time, but that support has EOLed.
https://vitess.io/docs/archive/13.0/overview/supported-databases/

2024-07-08 11:18 UTC, rcbensley commented on list-dba.md
> +| [Vitess](https://vitess.io/docs/19.0/reference/features/sharding/)  | Yes             | Apache 2.0         | Vitess is external to the database engine and also has migration strategies built in. |
Oh that's a shame. Removed.

2024-07-08 12:00 UTC, federico-razzoli approved these changes

2024-07-08 12:00 UTC, merged