POC mariadb proto extensions
Vettabase/awesome-mariadb pull request #23
Opened 2024-10-15 06:32 UTC by grooverdan

Proof of concept. I'm looking for way of putting driver support of https://mariadb.com/kb/en/mariadb-protocol-differences-with-mysql/ mapped out.

2024-10-15 08:07 UTC, grooverdan commented
Its a discussion on how to represent it. I'm not fixed on any particular format.

2024-10-15 11:36 UTC, federico-razzoli requested changes
Great additions! Some comments from me, but feel free to disagree:

1. Probably "Protocol Extensions" would be clearer? (Still not perfect, because one might wonder what exactly is extended)
2. Have you tried to use [lists](https://stackoverflow.com/a/19976953/9445059)? They might be more readable.
3. When the column's left blank, it's not clear if there are not extensions or we don't know. Where appropriate, I'd write `None`.

2024-10-15 22:07 UTC, grooverdan commented
> Great additions! Some comments from me, but feel free to disagree:
> 
>     1. Probably "Protocol Extensions" would be clearer? (Still not perfect, because one might wonder what exactly is extended)

sure.

>     2. Have you tried to use [lists](https://stackoverflow.com/a/19976953/9445059)? They might be more readable.

Good point. I'll adjust.

>     3. When the column's left blank, it's not clear if there are not extensions or we don't know. Where appropriate, I'd write `None`.

Ok. I'll make that clear.

For extensions I was thinking of making the following distinctions following the attribute abbreviation per connector:
* version of connector including the feature, and a link to documentation/interface.
* a `Requested` linking to a feature request if one has been made.
* a `N/A` (not applicable) if the extension is somehow unsuitable for the connector.
* a `No` if the feature request has been rejected by the upstream.
* a `Not present` if investigated and found to be missing.

It occurs to be basic protocol exposure of MySQL protocol could exist too. Like https://stackoverflow.com/questions/65136607/how-do-i-get-granular-load-data-results-from-the-golang-mysql-package/65136957#65136957 showing that there's a lack of OK packet decoding and making that available to the end user. I think this should be the same column?

Is this acceptable?

2024-10-15 23:18 UTC, federico-razzoli commented
@grooverdan Very informative. I approve it. If the table bloats too much, we can move these details to a new file with a 2-way table: the horizontal axis is the list of extensions and the vertical axis is the list of connectors.

2024-10-15 23:24 UTC, federico-razzoli commented
There's a conflict in table headers, please rebase or manually change a header.

2024-10-25 01:34 UTC, grooverdan commented
ready. Looks ok on my gh fork.

2024-10-26 12:49 UTC, merged

2024-10-26 14:32 UTC, grooverdan commented
Thanks @federico-razzoli