Dba and dev additions
Vettabase/awesome-mariadb pull request #7
Opened 2024-06-26 12:40 UTC by rcbensley

DBA and dev additions

2024-06-26 14:45 UTC, federico-razzoli requested changes
I have some objections and this PR is a bit big. I suggest you remove the new sections from here, and open separate PRs for them.
The others parts LGTM, except a couple of doubts, see the comments.

2024-06-26 14:45 UTC, federico-razzoli commented on list-dba.md
> +| [MyDumper](https://github.com/mydumper/mydumper)                      | YES                                  | GPLv3                                     | Parallel logical backups and restores. |
Does it really support MariaDB virtual columns, roles and other MariaDB specific syntax?
Also, with the latest improvements to mariadb-dump, is MyDumper still useful?

2024-06-26 14:45 UTC, federico-razzoli commented on list-dev.md
> +| Python               | [PyMySQL](https://github.com/PyMySQL/PyMySQL)                                             | YES             | Pure Python driver, MariaDB >= 10.4 |
As far as I can tell, it doesn't support non-blocking calls and progress reporting. If this is confirmed, I'd set MariaDB Support = 'PARTIAL'.

2024-06-26 15:33 UTC, rcbensley commented on list-dba.md
> +| [MyDumper](https://github.com/mydumper/mydumper)                      | YES                                  | GPLv3                                     | Parallel logical backups and restores. |
Very valid points. I shall remove this one.

2024-06-26 16:01 UTC, federico-razzoli requested changes

2024-06-26 16:01 UTC, federico-razzoli commented on list-dba.md
> +| [DataGrip](https://www.jetbrains.com/datagrip/)                             | [YES](https://www.jetbrains.com/datagrip/features/) | Linux, MacOS, Windows | Commercial     |       |
This table should mirror the one in list-dev, so make these changes there too.

2024-06-26 16:01 UTC, federico-razzoli commented on list-dev.md
> +- [NoSQL and Key Value Storage](https://github.com/Vettabase/awesome-mariadb/blob/main/list-dev.md#nosql-and-key-value-storage)
To be moved to a separate PR.

2024-06-27 10:37 UTC, federico-razzoli approved these changes

2024-06-27 10:38 UTC, merged